# Generated by Django 3.0.5 on 2020-05-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='identity',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='students',
            name='identity',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
