# Generated by Django 3.0.5 on 2020-05-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_auto_20200520_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='stu_class',
        ),
        migrations.RemoveField(
            model_name='students',
            name='stu_grade',
        ),
    ]
