# Generated by Django 3.0.5 on 2020-05-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_auto_20200520_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='stu_password',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
