# Generated by Django 3.0.5 on 2020-05-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_students_stu_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='stu_gender',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
