# Generated by Django 3.0.5 on 2020-05-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_auto_20200520_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='adm_password',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
