# Generated by Django 3.0.5 on 2020-05-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_admins_adm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='adm_gender',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
