# Generated by Django 3.0.5 on 2020-05-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_auto_20200521_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='stu_gender',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
