# Generated by Django 3.0.5 on 2020-05-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_auto_20200521_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_id', models.CharField(default='None', max_length=50)),
                ('com_startime', models.CharField(default='2018/10/10', max_length=50)),
                ('com_endtime', models.CharField(default='None', max_length=50)),
                ('com_type', models.CharField(default='None', max_length=50)),
                ('com_college', models.CharField(default='0', max_length=50)),
                ('com_total', models.CharField(default='None', max_length=50)),
            ],
        ),
    ]
