# Generated by Django 3.0.5 on 2020-05-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0009_competitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='com_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
