# Generated by Django 3.0.5 on 2020-05-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_competitions_com_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions',
            name='com_college',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='com_total',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
