# Generated by Django 3.0.5 on 2020-05-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0011_auto_20200525_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='com_stu',
            field=models.ManyToManyField(to='controller.Students'),
        ),
    ]
