# Generated by Django 3.0.5 on 2020-05-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0016_auto_20200526_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions',
            name='com_stu',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='cho_com', to='controller.Students'),
        ),
    ]
