# Generated by Django 3.0.5 on 2020-05-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0017_auto_20200526_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='com_mark',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
