# Generated by Django 3.0.5 on 2020-05-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0018_competitions_com_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions',
            name='com_mark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
