# Generated by Django 3.0.5 on 2020-06-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0021_notices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notices',
            old_name='not_name',
            new_name='noti_name',
        ),
    ]
